// Contract ABI for TradeLockEscrow and Standard ERC20 on BOT Chain Mainnet 677

export const TRADELOCK_ABI = [
  // --- Constructor ---
  {
    inputs: [
      { internalType: 'address', name: '_treasury', type: 'address' },
      { internalType: 'address', name: '_aiOracle', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },

  // --- Purchase Order Lifecycle ---
  {
    inputs: [
      { internalType: 'uint256', name: 'orderId', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'supplier', type: 'address' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint32', name: 'deliveryDeadline', type: 'uint32' },
          { internalType: 'uint16', name: 'productCategory', type: 'uint16' },
          { internalType: 'uint64', name: 'expectedQuantity', type: 'uint64' },
          { internalType: 'uint8', name: 'quantityUnit', type: 'uint8' },
          { internalType: 'bytes32', name: 'destination', type: 'bytes32' },
          { internalType: 'bytes32', name: 'orderRef', type: 'bytes32' },
          { internalType: 'bytes32', name: 'evidenceRequirementsHash', type: 'bytes32' },
        ],
        internalType: 'struct TradeLockEscrow.PurchaseOrderParams',
        name: 'params',
        type: 'tuple',
      },
    ],
    name: 'createPurchaseOrder',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'orderId', type: 'uint256' }],
    name: 'fundOrder',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'orderId', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'supplier', type: 'address' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint32', name: 'deliveryDeadline', type: 'uint32' },
          { internalType: 'uint16', name: 'productCategory', type: 'uint16' },
          { internalType: 'uint64', name: 'expectedQuantity', type: 'uint64' },
          { internalType: 'uint8', name: 'quantityUnit', type: 'uint8' },
          { internalType: 'bytes32', name: 'destination', type: 'bytes32' },
          { internalType: 'bytes32', name: 'orderRef', type: 'bytes32' },
          { internalType: 'bytes32', name: 'evidenceRequirementsHash', type: 'bytes32' },
        ],
        internalType: 'struct TradeLockEscrow.PurchaseOrderParams',
        name: 'params',
        type: 'tuple',
      },
    ],
    name: 'createAndFundOrder',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { internalType: 'bytes32', name: 'evidenceHash', type: 'bytes32' },
      { internalType: 'string', name: 'metadataUri', type: 'string' },
    ],
    name: 'submitEvidence',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { internalType: 'uint16', name: 'aiScore', type: 'uint16' },
      { internalType: 'enum TradeLockEscrow.AIRecommendation', name: 'recommendation', type: 'uint8' },
      { internalType: 'bytes32', name: 'aiReviewHash', type: 'bytes32' },
    ],
    name: 'submitAIVerification',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'orderId', type: 'uint256' },
      {
        components: [
          { internalType: 'uint256', name: 'orderId', type: 'uint256' },
          { internalType: 'bytes32', name: 'evidenceHash', type: 'bytes32' },
          { internalType: 'bytes32', name: 'reviewHash', type: 'bytes32' },
          { internalType: 'uint16', name: 'score', type: 'uint16' },
          { internalType: 'uint8', name: 'recommendation', type: 'uint8' },
          { internalType: 'uint256', name: 'nonce', type: 'uint256' },
          { internalType: 'uint256', name: 'deadline', type: 'uint256' },
        ],
        internalType: 'struct TradeLockEscrow.AIAttestation',
        name: 'attestation',
        type: 'tuple',
      },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
    ],
    name: 'approveAndReleaseWithAttestation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'orderId', type: 'uint256' },
      {
        components: [
          { internalType: 'uint256', name: 'orderId', type: 'uint256' },
          { internalType: 'bytes32', name: 'evidenceHash', type: 'bytes32' },
          { internalType: 'bytes32', name: 'reviewHash', type: 'bytes32' },
          { internalType: 'uint16', name: 'score', type: 'uint16' },
          { internalType: 'uint8', name: 'recommendation', type: 'uint8' },
          { internalType: 'uint256', name: 'nonce', type: 'uint256' },
          { internalType: 'uint256', name: 'deadline', type: 'uint256' },
        ],
        internalType: 'struct TradeLockEscrow.AIAttestation',
        name: 'attestation',
        type: 'tuple',
      },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
    ],
    name: 'releaseFundsWithAttestation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'orderId', type: 'uint256' }],
    name: 'releaseFunds',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'orderId', type: 'uint256' }],
    name: 'refundBuyer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { internalType: 'bytes32', name: 'reasonHash', type: 'bytes32' },
    ],
    name: 'disputeOrder',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },

  // --- View Functions ---
  {
    inputs: [{ internalType: 'uint256', name: 'orderId', type: 'uint256' }],
    name: 'getOrder',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'buyer', type: 'address' },
          { internalType: 'enum TradeLockEscrow.OrderStatus', name: 'status', type: 'uint8' },
          { internalType: 'enum TradeLockEscrow.AIRecommendation', name: 'aiRecommendation', type: 'uint8' },
          { internalType: 'uint16', name: 'feeBps', type: 'uint16' },
          { internalType: 'uint16', name: 'aiScore', type: 'uint16' },
          { internalType: 'uint32', name: 'createdAt', type: 'uint32' },
          { internalType: 'uint16', name: 'productCategory', type: 'uint16' },
          { internalType: 'address', name: 'supplier', type: 'address' },
          { internalType: 'uint32', name: 'deliveryDeadline', type: 'uint32' },
          { internalType: 'uint32', name: 'fundedAt', type: 'uint32' },
          { internalType: 'uint32', name: 'settledAt', type: 'uint32' },
          { internalType: 'address', name: 'token', type: 'address' },
          { internalType: 'uint64', name: 'expectedQuantity', type: 'uint64' },
          { internalType: 'uint8', name: 'quantityUnit', type: 'uint8' },
          { internalType: 'uint24', name: '__reserved', type: 'uint24' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'bytes32', name: 'destination', type: 'bytes32' },
          { internalType: 'bytes32', name: 'orderRef', type: 'bytes32' },
          { internalType: 'bytes32', name: 'evidenceRequirementsHash', type: 'bytes32' },
          { internalType: 'bytes32', name: 'evidenceHash', type: 'bytes32' },
          { internalType: 'bytes32', name: 'aiReviewHash', type: 'bytes32' },
        ],
        internalType: 'struct TradeLockEscrow.Order',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getOrderCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAllOrderIds',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'totalEscrowed',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'treasury',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'aiOracle',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'disputeAdmin',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'feeBps',
    outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    stateMutability: 'view',
    type: 'function',
  },

  // --- Events ---
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: true, internalType: 'address', name: 'supplier', type: 'address' },
      { indexed: false, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint32', name: 'deliveryDeadline', type: 'uint32' },
      { indexed: false, internalType: 'uint16', name: 'productCategory', type: 'uint16' },
      { indexed: false, internalType: 'uint64', name: 'expectedQuantity', type: 'uint64' },
      { indexed: false, internalType: 'uint8', name: 'quantityUnit', type: 'uint8' },
      { indexed: false, internalType: 'bytes32', name: 'destination', type: 'bytes32' },
      { indexed: false, internalType: 'bytes32', name: 'orderRef', type: 'bytes32' },
      { indexed: false, internalType: 'bytes32', name: 'evidenceRequirementsHash', type: 'bytes32' },
    ],
    name: 'PurchaseOrderCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: false, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint16', name: 'feeBps', type: 'uint16' },
    ],
    name: 'PurchaseOrderFunded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'supplier', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'evidenceHash', type: 'bytes32' },
      { indexed: false, internalType: 'string', name: 'metadataUri', type: 'string' },
    ],
    name: 'EvidenceSubmitted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { indexed: false, internalType: 'uint16', name: 'aiScore', type: 'uint16' },
      { indexed: false, internalType: 'enum TradeLockEscrow.AIRecommendation', name: 'recommendation', type: 'uint8' },
      { indexed: false, internalType: 'bytes32', name: 'aiReviewHash', type: 'bytes32' },
    ],
    name: 'AIVerified',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: true, internalType: 'address', name: 'supplier', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'netAmount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'feeAmount', type: 'uint256' },
    ],
    name: 'FundsReleased',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'refundAmount', type: 'uint256' },
    ],
    name: 'OrderRefunded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'orderId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'initiator', type: 'address' },
      { indexed: false, internalType: 'bytes32', name: 'reasonHash', type: 'bytes32' },
    ],
    name: 'OrderDisputed',
    type: 'event',
  },
] as const;

export const ERC20_ABI = [
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function decimals() view returns (uint8)',
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address account) view returns (uint256)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 value) returns (bool)',
  'function transfer(address to, uint256 value) returns (bool)',
  'function transferFrom(address from, address to, uint256 value) returns (bool)',
] as const;
